# -*- coding: utf-8 -*-
"""skintypeDensenet169.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfhryE7wCHH2X0neXIc3ZfC9vwDdp7R4
"""

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.python.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

import zipfile

zip_ref = zipfile.ZipFile('/content/drive/MyDrive/datasets/train.zip','r')
zip_ref.extractall('/tmp')
zip_ref.close()

zip_ref = zipfile.ZipFile('/content/drive/MyDrive/datasets/valid.zip','r')
zip_ref.extractall('/tmp')
zip_ref.close()

zip_ref = zipfile.ZipFile('/content/drive/MyDrive/datasets/test.zip','r')
zip_ref.extractall('/tmp')
zip_ref.close()

# prompt: different class names

base_dir = '/tmp/train/'
class_names = os.listdir(base_dir)
print(class_names)

keras_model = Sequential()

pretrained_model= tf.keras.applications.DenseNet169(include_top=False,
                   input_shape=(640,640,3),
                   pooling='avg',classes=3,
                   weights='imagenet')
for layer in pretrained_model.layers:
        layer.trainable=False

keras_model.add(pretrained_model)
keras_model.add(Flatten())
keras_model.add(Dense(512, activation='relu'))
keras_model.add(Dense(3, activation='softmax'))

keras_model.summary()

keras_model.compile(optimizer=Adam(learning_rate=0.001),loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define data generators for training, validation, and test sets
train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
        '/tmp/train/',
        target_size=(640, 640),
        batch_size=32,
        class_mode='categorical')

valid_datagen = ImageDataGenerator(rescale=1./255)
validation_generator = valid_datagen.flow_from_directory(
        '/tmp/valid/',
        target_size=(640, 640),
        batch_size=32,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
        '/tmp/test/',
        target_size=(640, 640),
        batch_size=32,
        class_mode='categorical')

# Fit the model using the generators
history = keras_model.fit(
      train_generator,
      steps_per_epoch=train_generator.samples/train_generator.batch_size,
      validation_data=validation_generator,
      validation_steps=validation_generator.samples/validation_generator.batch_size,
      epochs=20)

test_loss, test_acc = keras_model.evaluate(test_generator, verbose=2)
print('\nTest accuracy:', test_acc)

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.grid()
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epochs')
plt.legend(['train', 'validation'])
plt.show()

import math

# Evaluate the model using the test generator
steps = math.ceil(test_generator.samples / test_generator.batch_size)
test_loss, test_accuracy = keras_model.evaluate(test_generator, steps=steps)
print(f"Test Accuracy: {test_accuracy:.4f}")

# Make predictions on the test set
test_generator.reset()  # Reset the generator to start from the beginning
predictions = keras_model.predict(test_generator, steps=steps, verbose=1)

# Get the class indices and labels
class_indices = test_generator.class_indices
labels = list(class_indices.keys())

# Function to decode predictions
def decode_predictions(predictions, labels, top=5):
    decoded = []
    for pred in predictions:
        top_indices = pred.argsort()[-top:][::-1]
        top_labels = [labels[i] for i in top_indices]
        top_scores = [pred[i] for i in top_indices]
        decoded.append(list(zip(top_labels, top_scores)))
    return decoded

# Decode the predictions
decoded_predictions = decode_predictions(predictions, labels)

# Print the predictions for the first few test images
for i in range(min(len(decoded_predictions), 5)):
    print(f"Test Image {i+1}:")
    for label, score in decoded_predictions[i]:
        print(f"   Label: {label}, Confidence: {score:.4f}")

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# Function to load and preprocess a single image
def load_and_preprocess_image(img_path, target_size=(640, 640)):
    img = image.load_img(img_path, target_size=target_size)
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    img_array = img_array / 255.0  # Rescale to [0, 1] if you used rescale=1./255 in ImageDataGenerator
    return img_array

# Function to predict the class of a single image
def predict_image_class(model, img_path, class_indices):
    # Load and preprocess the image
    img_array = load_and_preprocess_image(img_path)

    # Make prediction
    predictions = model.predict(img_array)

    # Get the class labels
    labels = list(class_indices.keys())

    # Decode the prediction
    top_index = np.argmax(predictions[0])
    top_label = labels[top_index]
    top_confidence = predictions[0][top_index]

    return top_label, top_confidence

# Assuming class indices from the test generator
class_indices = {'acne': 0, 'dry': 1, 'oily': 2}

# Path to the image you want to predict
test_image_path = '/content/drive/MyDrive/datasets/acne.jpg'  # Replace with your test image path

# Predict the class of the test image
predicted_label, confidence = predict_image_class(keras_model, test_image_path, class_indices)

# Print the prediction
print(f"The image belongs to: {predicted_label} with confidence: {confidence:.4f}")

# Optionally, display the image
img = image.load_img(test_image_path, target_size=(640, 640))
plt.imshow(img)
plt.title(f"Predicted: {predicted_label} ({confidence:.4f})")
plt.axis('off')
plt.show()

#product_dataset_path = '/content/drive/MyDrive/dataset/result.csv'
#products_df = pd.read_csv(product_dataset_path)

#products_df

#products_df['skin type'].fillna("Unknown", inplace=True)

# Filter products for only 'oily', 'acne', and 'dry' skin types
#filtered_products_df = products_df[products_df['skin type'].str.contains('oily|acne|dry', case=False)]

# Function to recommend products based on skin type
#def recommend_products(skin_type):
    #recommended_products = filtered_products_df[filtered_products_df['skin type'].str.contains(skin_type, case=False)]
    #return recommended_products.to_dict(orient='records')
#def recommend_products(skin_type, top_n=5):
 #   recommended_products = filtered_products_df[filtered_products_df['skin type'].str.contains(skin_type, case=False)]
  #  top_recommended_products = recommended_products.head(top_n)
   # return top_recommended_products.to_dict(orient='records')
# Recommend products based on the predicted skin type
#recommended_products = recommend_products(predicted_label)
#print(recommended_products)

